# GoReleaser configuration for xyzduck
# Used only for building binaries via `goreleaser build --single-target`
# Release creation is handled by GitHub Actions workflow

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X org.xyzmaps.xyzduck/src/version.Version={{.Version}}
      - -X org.xyzmaps.xyzduck/src/version.Commit={{.Commit}}
      - -X org.xyzmaps.xyzduck/src/version.Date={{.Date}}

# Archives, changelog, and release sections are not used
# Release artifacts are created by GitHub Actions workflow
